
    <div class="container">
        <h1 class="mt-5">Activity Log</h1>
        <ul class="list-group mt-3">
            <li class="list-group-item">User A logged in</li>
            <li class="list-group-item">User B updated their profile</li>
            <li class="list-group-item">User C created a new post</li>
            <li class="list-group-item">User A logged out</li>
            <li class="list-group-item">User D deleted a comment</li>
            <li class="list-group-item">User A logged in</li>
            <li class="list-group-item">User B updated their profile</li>
            <li class="list-group-item">User C created a new post</li>
            <li class="list-group-item">User A logged out</li>
            <li class="list-group-item">User D deleted a comment</li>
            <li class="list-group-item">User A logged in</li>
            <li class="list-group-item">User B updated their profile</li>
            <li class="list-group-item">User C created a new post</li>
            <li class="list-group-item">User A logged out</li>
            <li class="list-group-item">User D deleted a comment</li>
            <li class="list-group-item">User A logged in</li>
            <li class="list-group-item">User B updated their profile</li>
            <li class="list-group-item">User C created a new post</li>
            <li class="list-group-item">User A logged out</li>
            <li class="list-group-item">User D deleted a comment</li>
            <li class="list-group-item">User A logged in</li>
            <li class="list-group-item">User B updated their profile</li>
            <li class="list-group-item">User C created a new post</li>
            <li class="list-group-item">User A logged out</li>
            <li class="list-group-item">User D deleted a comment</li>
            <li class="list-group-item">User A logged in</li>
            <li class="list-group-item">User B updated their profile</li>
            <li class="list-group-item">User C created a new post</li>
            <li class="list-group-item">User A logged out</li>
            <li class="list-group-item">User D deleted a comment</li>
            <li class="list-group-item">User A logged in</li>
            <li class="list-group-item">User B updated their profile</li>
            <li class="list-group-item">User C created a new post</li>
            <li class="list-group-item">User A logged out</li>
            <li class="list-group-item">User D deleted a comment</li>
            <li class="list-group-item">User A logged in</li>
            <li class="list-group-item">User B updated their profile</li>
            <li class="list-group-item">User C created a new post</li>
            <li class="list-group-item">User A logged out</li>
            <li class="list-group-item">User D deleted a comment</li>
            <li class="list-group-item">User A logged in</li>
            <li class="list-group-item">User B updated their profile</li>
            <li class="list-group-item">User C created a new post</li>
            <li class="list-group-item">User A logged out</li>
            <li class="list-group-item">User D deleted a comment</li>
            <li class="list-group-item">User A logged in</li>
            <li class="list-group-item">User B updated their profile</li>
            <li class="list-group-item">User C created a new post</li>
            <li class="list-group-item">User A logged out</li>
            <li class="list-group-item">User D deleted a comment</li>
            <li class="list-group-item">User A logged in</li>
            <li class="list-group-item">User B updated their profile</li>
            <li class="list-group-item">User C created a new post</li>
            <li class="list-group-item">User A logged out</li>
            <li class="list-group-item">User D deleted a comment</li>
            <li class="list-group-item">User A logged in</li>
            <li class="list-group-item">User B updated their profile</li>
            <li class="list-group-item">User C created a new post</li>
            <li class="list-group-item">User A logged out</li>
            <li class="list-group-item">User D deleted a comment</li>
        </ul>
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

